### ISSUE TITLE
Test Google Sheets integration

### ISSUE THREAD

**Issue by eddieantonio** [eddieantonio/predictive-text-studio#198]
Ensure the Google Sheets integration works with valid links and provides **helpful/actionable feedback** when things go wrong.

**Comment by ChrisChrisLoLo** [comment]
@eddieantonio We might need you to create an encrypted secret so that way the Github Actions runner can use it to enable the Google Sheets API. I cannot access the settings tab for this repo, so I do not think I can tinker around with the following steps: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository

**Comment by eddieantonio** [comment]
I added `GOOGLE_SHEETS_API_KEY` and `GOOGLE_SHEETS_CLIENT_ID` to the repository secrets 👍🏼 

You can use them in GitHub Actions as:

```yaml
env:
  API_KEY: ${ secrets.GOOGLE_SHEETS_API_KEY }
  CLIENT_ID: ${ secrets.GOOGLE_SHEETS_CLIENT_ID }
```

No need to juggle things in the `.env` file (at least, theoretically 🤞🏼 )
